<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-04 at 00:22:04.
 */
class Number extends PHPUnit_Framework_TestCase
{
    /**
     * @var Number
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Base\Number(4);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Base\Number::equals
     */
    public function testEquals()
    {
        $this->assertEquals(4, $this->object->equals());
    }

    /**
     * @covers Base\Number::plus
     */
    public function testPlus()
    {
        $this->assertEquals(5, $this->object->plus(1)->equals());
    }

    /**
     * @covers Base\Number::minus
     */
    public function testMinus()
    {
        $this->assertEquals(3, $this->object->minus(1)->equals());
    }

    /**
     * @covers Base\Number::divided_by
     */
    public function testDivided_by()
    {
        $this->assertEquals(2, $this->object->divided_by(2)->equals());
    }

    /**
     * @covers Base\Number::times
     */
    public function testTimes()
    {
        $this->assertEquals(8, $this->object->times(2)->equals());
    }
}
